repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: requirements-txt-fixer
    -   id: check-yaml
    -   id: check-json
    -   id: detect-private-key
    -   id: check-case-conflict
    -   id: check-ast
    -   id: debug-statements
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
    -   id: ruff
        args: [--fix]
    -   id: ruff-format
-   repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    -   id: bandit
        args: ['--severity-level', 'medium', '--confidence-level', 'high']
        files: ^backend/
